name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Docker Build
      run: |
        docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }} &&
        docker build ./ -t dotnet-core-sqlite-swagger-rest-api:latest &&
        docker tag dotnet-core-sqlite-swagger-rest-api:latest maheshkareeya/dotnet-core-sqlite-swagger-rest-api:latest &&
        docker push maheshkareeya/dotnet-core-sqlite-swagger-rest-api:latest
        
